function [R, rightAscension, declination] = elevationAndAzimuthToRAandDec...
    (baseStationEastLongitude, baseStationLatitude, elevation, azimuth,...
    localSiderealTime)


    QxX = [-sind(localSiderealTime), ...
        -sind(baseStationLatitude)*cosd(localSiderealTime), ...
        cosd(baseStationLatitude)*cosd(localSiderealTime);...
        cosd(localSiderealTime), ...
        -sind(baseStationLatitude)*sind(localSiderealTime),...
        cosd(baseStationLatitude)*sind(localSiderealTime);...
        0, cosd(baseStationLatitude), sind(baseStationLatitude)];
    
    row = [cosd(elevation)*sind(azimuth); cosd(elevation)*cosd(azimuth);...
        sind(elevation)];
    
    rowPrime = QxX*row;
    
    declination = asind(rowPrime(3));
    
    if(row(2) > 0)
        rightAscension = acosd(rowPrime(1)/cosd(declination));
    else
        rightAscension = 360 - acosd(rowPrime(1)/cosd(declination));
    end
    R = rowPrime;
end