function Rperifocal = stateVectorToPerifocalFrame(R, RAAN, i, perigee)

    QXx = [-sind(RAAN)*cosd(i)*sind(perigee)+cosd(RAAN)*cosd(perigee), ...
        cosd(RAAN)*cosd(i)*cosd(perigee)+sind(RAAN)*cosd(perigee), ...
        sind(i)*sind(perigee);
        -sind(RAAN)*cosd(i)*cosd(perigee)-cosd(RAAN)*sind(perigee),...
        cosd(RAAN)*cosd(i)*cosd(perigee)-sind(RAAN)*sind(perigee),...
        sind(i)*cosd(perigee);...
        sind(RAAN)*sind(i), -cosd(RAAN)*sind(i), cosd(i)];
    
    Rperifocal = QXx*R;

end